package cn.blur.self.module;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.


/**
 * Entity mapped to table RESOURCE_TEMP.
 */
public class ResourceTemp implements java.io.Serializable {

    private String res_name;
    private String res_title;
    private String background_img;
    private String share_msg;
    private String active_msg;
    private String install_msg;
    private String download_msg;
    private Integer res_type;
    private Integer download_score;
    private Integer install_score;
    private Integer share_score;
    private String download_num;
    private Integer active_score;
    private Integer share_status;


    public String getRes_name() {
        return res_name;
    }

    public void setRes_name(String res_name) {
        this.res_name = res_name;
    }
    public String getRes_title() {
        return res_title;
    }

    public void setRes_title(String res_title) {
        this.res_title = res_title;
    }

    public String getBackground_img() {
        return background_img;
    }

    public void setBackground_img(String background_img) {
        this.background_img = background_img;
    }

    public String getShare_msg() {
        return share_msg;
    }

    public void setShare_msg(String share_msg) {
        this.share_msg = share_msg;
    }

    public String getActive_msg() {
        return active_msg;
    }

    public void setActive_msg(String active_msg) {
        this.active_msg = active_msg;
    }

    public String getInstall_msg() {
        return install_msg;
    }

    public void setInstall_msg(String install_msg) {
        this.install_msg = install_msg;
    }

    public String getDownload_msg() {
        return download_msg;
    }

    public void setDownload_msg(String download_msg) {
        this.download_msg = download_msg;
    }

    public Integer getRes_type() {
        return res_type;
    }

    public void setRes_type(Integer res_type) {
        this.res_type = res_type;
    }


    public Integer getDownload_score() {
        return download_score;
    }

    public void setDownload_score(Integer download_score) {
        this.download_score = download_score;
    }

    public Integer getInstall_score() {
        return install_score;
    }

    public void setInstall_score(Integer install_score) {
        this.install_score = install_score;
    }

    public Integer getShare_score() {
        return share_score;
    }

    public void setShare_score(Integer share_score) {
        this.share_score = share_score;
    }

    public String getDownload_num() {
        return download_num;
    }

    public void setDownload_num(String download_num) {
        this.download_num = download_num;
    }

    public Integer getActive_score() {
        return active_score;
    }

    public void setActive_score(Integer active_score) {
        this.active_score = active_score;
    }

    public Integer getShare_status() {
        return share_status;
    }

    public void setShare_status(Integer share_status) {
        this.share_status = share_status;
    }

}
